name: Prune all untagged packages

on:
    - workflow_dispatch

jobs:
    prune:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

    
        steps:
        - name: Login
          uses: "docker/login-action@v3.3.0"
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: Prune Containers
          uses: "lannonbr/prune-containers-action@1.0.1"
          with:
            container-name: "astro-site/astro-site"
            