name: Prune all untagged packages

on:
    - workflow_dispatch

jobs:
    prune:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

    
        steps:
        - name: Login
          uses: "docker/login-action@v3.3.0"
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: Delete Old Tagged Packages
          uses: emmahsax/action-ghcr-prune@main
          with:
              container: ${{ github.event.repository.name }}
              dry-run: true
              keep-last: 5
              keep-tags-regexes: |
                ^latest$
                ^sha-$
              organization: ${{ github.repository_owner }}
              prune-tags-regexes: |
                .+
              remove-multi-platform: true
              token: ${{ secrets.GITHUB_TOKEN }}
    
          # After the first step finishes, then go through and delete all other untagged packages
          # UNLESS they are a part of a multi-arch image that is left around from the first step.
        - name: Delete Old Untagged Packages
          uses: emmahsax/action-ghcr-prune@main
          with:
              container: astro-site/astro-site
              dry-run: true
              keep-last: 0
              organization: ${{ github.repository_owner }}
              prune-untagged: true
              token: ${{ secrets.GITHUB_TOKEN }}